[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn publisher.wsgi --bind 0.0.0.0:$PORT --log-file -"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
