# Generated by Django 4.2.30 on 2026-05-11 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('kicker_color', models.CharField(default='#A8231F', help_text='Hex color for the section kicker label', max_length=20)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('dek', models.TextField(help_text='One- or two-sentence subhead shown under the headline')),
                ('body', models.JSONField(blank=True, default=list)),
                ('hero_image_url', models.URLField(blank=True)),
                ('hero_caption', models.CharField(blank=True, max_length=240)),
                ('template', models.CharField(choices=[('classic', 'Classic - narrow column, drop cap'), ('full-bleed', 'Full-bleed - large hero image'), ('immersive', 'Immersive - dark, image-driven')], default='classic', help_text='Editorial layout variant for this story', max_length=20)),
                ('is_cover', models.BooleanField(default=False, help_text='Promote this article to the cover-story slot on the homepage')),
                ('cloak_enabled', models.BooleanField(default=False, help_text='Inject the Cloak SDK script in the <head> for this article only')),
                ('extra_head_script_url', models.URLField(blank=True, help_text='Optional URL of an extra script to load in <head> before any body content paints')),
                ('read_minutes', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='editorial.author')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='editorial.section')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='editorial_a_publish_ae991b_idx'), models.Index(fields=['is_published', '-published_at'], name='editorial_a_is_publ_398a92_idx')],
            },
        ),
    ]
