# Generated by Django 4.2.30 on 2026-05-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cloak_enabled',
        ),
        migrations.RemoveField(
            model_name='article',
            name='extra_head_script_url',
        ),
    ]
